services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: literature_web
    restart: unless-stopped
    environment:
      DATABASE_URL: sqlite:///./data/literature.db
      UPLOAD_DIR: /app/uploads
    ports:
      - "20766:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
